name: hummingbird-child
display_name: Hummingbird Child
version: 1.0.0
author:
  name: "Your Name"
  email: "you@email.com"
  url: "https://example.com"

parent: hummingbird

assets:
  use_parent_assets: true
